### PR TITLE
Check the action still exists before running it

### PR DESCRIPTION
**Pull request by polevaultweb**
Resolves https://github.com/wpninjas/ninja-forms/issues/1736

### CODE REVIEW

**Comment by polevaultweb** [comment]
@kjohnson this was causing a Fatal on form submission

**Comment by kjohnson** [comment]
Looks like it was fixed in `run_actions()`, but not `run_actions_preview()`. Good catch.

Another reason to refactor published/preview data structures for using a single process.

**Comment by kjohnson** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;zx2pYOpV&#x2F;27-check-the-action-still-exists-before-running-it"> Check the action still exists before running it</a>

**Comment by klhall1987** [comment]
Tested working, correctly, and ready for merge. Passing to @kjohnson for merge.

**Pull request merged**
