### PR TITLE
Broken Checkbox Lists in Submissions

### PR DESCRIPTION
**Pull request by Much2tall**
Added array check to sweep out invalid values from conditionally hidden Checkbox List Fields.

### CODE REVIEW

**Comment by Much2tall** [comment]
Closes: https://github.com/wpninjas/ninja-forms/issues/2711

**Comment by Much2tall** [comment]
Should work properly now.

**Comment by kstover** [comment]
Well, while looking into this bug, I found another with editing submissions with checkbox lists within the admin.

If you edit the submission by unchecking every option, your changes aren't saved. You can uncheck everything but one, and it will save. When you try to save with NO options checked, it will return to its original state.

**Comment by Much2tall** [comment]
@kstover 
I did some checking, and that issue also appears on the master branch.

**Comment by Much2tall** [comment]
@kstover 
Issue should now be resolved.

**Pull request merged**
