### PR TITLE
Override the edit post URL with the edit form URL in the form preview

### PR DESCRIPTION
**Pull request by polevaultweb**
Resolves https://github.com/wpninjas/ninja-forms/issues/1720

### CODE REVIEW

**Comment by kjohnson** [comment]
Ah, brilliant.

**Comment by kstover** [comment]
@kjohnson @polevaultweb Would this mean clicking the "Edit" button takes you to edit the form instead of the post?

**Comment by jameslaws** [comment]
If we can do it easy enough, I think this makes sense on the preview page since it's not actually a page.

**Comment by kjohnson** [comment]
@kstover yes, as opposed to editing the page that the preview leverages.
@jameslaws I agree that this would be more contextually correct.

**Comment by polevaultweb** [comment]
@kjohnson `master` merged in, no conflicts

**Pull request merged**
