### PR TITLE
Submissions display

### PR DESCRIPTION
**Pull request by kjohnson**
Adds an advanced form setting for displaying submissions in a loop with custom HTML and Merge Tag templating.

Adds Shortcode: `[ninja_forms_subs form_id=1]`

### CODE REVIEW

**Comment by kjohnson** [comment]
## Advanced Builder Settings

screenshot 2016-08-31 12 52 10

**Comment by kjohnson** [comment]
## Front End Display

screenshot 2016-08-31 12 39 17

**Comment by klhall1987** [comment]
Tested and working correctly. Passing to @kstover for merge.

**Comment by kjohnson** [comment]
https://wpninjas.kustomerapp.com/app/customers/58151b6fcffc05110088fed4/event/5816332b0b0ff4110031ecb9

**Comment by kjohnson** [comment]
Closing in favor of development via a feature plugin ([wpninjas/ninja-forms-submissions-display](https://github.com/wpninjas/ninja-forms-submissions-display)).

**Pull request closed without merging**
