### PR TITLE
Update "input limit" setting names for conversion

### PR DESCRIPTION
**Pull request by kjohnson**

### CODE REVIEW

**Comment by klhall1987** [comment]
@kjohnson I found two other small issues I think issue #1374 is a bit more pressing than #1375 

issue #1375 

issue #1374

**Comment by kjohnson** [comment]
Passing back to @klhall1987 for testing.

**Comment by klhall1987** [comment]
Passing back to @kjohnson found a blocker see issue #1379

**Comment by kjohnson** [comment]
AGAIN! @klhall1987

**Comment by klhall1987** [comment]
Fix confirmed ready for merge

**Pull request merged**
