### PR TITLE
Restore progress anim image

### PR DESCRIPTION
**Pull request by timarney**
The progress animation image is throwing a 404.  The PR restores that image.

Fixes https://github.com/wpninjas/ninja-forms/issues/2154

screen shot 2017-01-30 at 7 00 54 pm

### CODE REVIEW

**Comment by kstover** [comment]
@timarney Could you re-pull develop and then re-submit this PR? I can clean it up, but that seems like a simpler alternative.

**Comment by kstover** [comment]
Make sure to pull it against the develop branch.

**Comment by timarney** [comment]
Sure thing.

**Comment by timarney** [comment]
@kstover 

Just making sure I have the steps correct here

I did the regular add **remote add upstream**  
https://help.github.com/articles/configuring-a-remote-for-a-fork

And **sync** process
https://help.github.com/articles/syncing-a-fork

```
* [new branch]      desk14862  -> upstream/desk14862
* [new branch]      desk19707  -> upstream/desk19707
* [new branch]      develop    -> upstream/develop
* [new branch]      develop-2c65e2d7 -> upstream/develop-2c65e2d7
```
Seeing the branches etc...

Do I make a pull request from my master to the develop branch?

**Comment by kstover** [comment]
@timarney Yep. You just want to merge into develop instead of master.

**Comment by timarney** [comment]
https://github.com/wpninjas/ninja-forms/pull/2398

**Pull request closed without merging**
