### PR TITLE
Fix initial required check for list fields

### LINKED ISSUE #1482: Required multi-select and checkbox list fields are breaking on the front end in 3.0
In the 3.0 code base, if a form has a multi-select or checkbox list field that is set to be required and does not have a default value selected then, when the form is viewed on the front-end end the multi-select field and everything after isn't being displayed. There is a JS error appearing in the console. I've detailed the error in the screen shot below. 

Screenshot: 
screen shot 2016-07-06 at 2 00 04 pm

Replication Steps(in the 3.0 codebase):
1. Create a form.
2. Add a multi-select field and submit button.
3. Edit the multi-select and make it a required field. 
4. Preview the form.

### PR DESCRIPTION
**Pull request by kjohnson**
Closes #1482

### CODE REVIEW

**Comment by kjohnson** [comment]
Ok, so, we really need to fix this gulp/re-gulp thing.

**Comment by klhall1987** [comment]
The Multi-select/checkbox list required fields with no default values are no longer breaking display on the front end; however, if a multi-select or checkbox field is present the form will no long submit. I've take a screenshot of what I'm seeing in the network tab in the admin-ajax.php response.   

Screenshot
screen shot 2016-07-19 at 11 39 27 am

**Comment by kjohnson** [comment]
@klhall1987 back to you for testing.

**Comment by klhall1987** [comment]
Tested and working correctly passing to @kstover for merge.

**Pull request merged**
