### PR TITLE
Removed disable input and input limit on the credit card fields. 

### LINKED ISSUE #1525: Remove restriction settings from credit card field in 3.0
Remove the restriction settings from the credit card field in 3.0

### PR DESCRIPTION
**Pull request by klhall1987**
Removed disable input and input limit on the credit card fields. Closes #1525

### CODE REVIEW

**Comment by kjohnson** [comment]
@klhall1987 The `CreditCardZip` field still has an `input_limit_set` setting.

**Comment by klhall1987** [comment]
@kjohnson I thought users might need to set an input limit on the creditcardzip field. Or can they just use an input mask to do this?

**Comment by kjohnson** [comment]
@klhall1987 My guess is zip codes would be an input mask, if anything. Also, different areas have different zip code formats.

Any thoughts, @kstover ?

**Comment by kstover** [comment]
I'd say it has an input mask.

**Pull request merged**
