### PR TITLE
Fix a bug with updating form error messages on submission.

### LINKED ISSUE #1801: Form error messages do not update
If a form submission returns an error, then the form is re-submitted, the form error is not updated to reflect the new error returned by the form submission.

### PR DESCRIPTION
**Pull request by kjohnson**
Closes #1801.

### CODE REVIEW

**Comment by klhall1987** [comment]
@kjohnson I'm unsure of how to test this PR. Could you give me some replication steps to test with?

**Comment by kjohnson** [comment]
@klhall1987 the issues was with error messages not updating under the same domain.

For example, on form submisson an action, let's say "MailChimp", returns an error:
`$data[ 'errors' ][ 'form' ][ 'mailchimp' ] = 'Invalid email.';`

The submission halts and dispalys the error on the form.

After fixing the error and re-submitting, any errors returned under the same key (`[ 'errors' ][ 'form' ][ 'mailchimp' ]`) are not displayed and the origional error message is not cleared.

**Comment by klhall1987** [comment]
Okay cool, I'll try to replicate.

**Comment by klhall1987** [comment]
@kjohnson tested and said it was working. Marking as ready and passing to @kstover for merge.

**Pull request merged**
