### PR TITLE
Correct the case of the filename of NF_Fields_ListSelect (Issue #2255)

### LINKED ISSUE #2255: NF_Fields_ListSelect in file LIstState.php has type-o (case) in filename
```
 $ find . -type f -name '*LIstState*'
./includes/Fields/LIstState.php

 $ grep -nR 'LIstState' .
./lang/ninja-forms-tl.po:6114:#: includes/Fields/LIstState.php:26
./lang/ninja-forms-ru_RU.po:6131:#: includes/Fields/LIstState.php:26
./lang/ninja-forms-it_IT.po:6136:#: includes/Fields/LIstState.php:26
./lang/ninja-forms-ko_KR.po:6001:#: includes/Fields/LIstState.php:26
./lang/ninja-forms-nb_NO.po:6127:#: includes/Fields/LIstState.php:26
./lang/ninja-forms-zh_TW.po:5959:#: includes/Fields/LIstState.php:26
./lang/ninja-forms-id_ID.po:6128:#: includes/Fields/LIstState.php:26
./lang/ninja-forms-hi_IN.po:6114:#: includes/Fields/LIstState.php:26
./lang/ninja-forms-da_DK.po:6137:#: includes/Fields/LIstState.php:26
./lang/ninja-forms-ja.po:5989:#: includes/Fields/LIstState.php:26
./lang/ninja-forms-pt_PT.po:6149:#: includes/Fields/LIstState.php:26
./lang/ninja-forms-es_MX.po:6147:#: includes/Fields/LIstState.php:26
./lang/ninja-forms-es_ES.po:6147:#: includes/Fields/LIstState.php:26
./lang/ninja-forms-fr_FR.po:6151:#: includes/Fields/LIstState.php:26
./lang/ninja-forms-pl_PL.po:6127:#: includes/Fields/LIstState.php:26
./lang/ninja-forms-de_DE.po:6152:#: includes/Fields/LIstState.php:26
./lang/ninja-forms-pt_BR.po:6131:#: includes/Fields/LIstState.php:26
./lang/ninja-forms-mr.po:6114:#: includes/Fields/LIstState.php:26
./lang/ninja-forms.pot:5950:#: includes/Fields/LIstState.php:26
./lang/ninja-forms-vi.po:6107:#: includes/Fields/LIstState.php:26
```

### PR DESCRIPTION
**Pull request by isleshocky77**
Fixes #2255

### CODE REVIEW

**Comment by kjohnson** [comment]
@isleshocky77 is the type-o causing issues with loading translations?

**Comment by isleshocky77** [comment]
Not that I know of. It was just annoying me while working in the code.

**Comment by isleshocky77** [comment]
@kstover Which tag did this make it into?

**Comment by isleshocky77** [comment]
It appears this should have been tagged with [3.0.21](https://github.com/wpninjas/ninja-forms/releases/tag/3.0.21)

**Pull request merged**
