### PR TITLE
Remove Freemius and add basic tracking opt-in

### PR DESCRIPTION
**Pull request by kjohnson**

### CODE REVIEW

**Comment by jameslaws** [comment]
When I try the Konami code or the NF_DEV constant, neither work to allow me to switch to 3.0 with this.

**Comment by kjohnson** [comment]
@jameslaws both methods work for me.

**Comment by jameslaws** [comment]
Yeah, can't get it to work on a clean install and this branch. Neither way works and no upgrade is ever available.

**Comment by klhall1987** [comment]
I currently have Conditional Logic and Layout and Styles installed. If Conditional Logic and Layout and Styles are both active, I can use the Konami Code to get to the upgrade screen but the upgrade fails. However, If I deactivate Conditional Logic and only Layout and Styles is active I can use the Konami Code and upgrade to 3.0

**Comment by klhall1987** [comment]
After further examination, the issue mentioned above looks to be an issue is in the master branch itself. I'll make an issue for that to be looked into.

**Comment by klhall1987** [comment]
Tested and seems to be working properly.

**Comment by kjohnson** [comment]
@klhall1987 Can you details what tests you ran?

**Comment by klhall1987** [comment]
@kjohnson I tested updating, rollingback, basic form building in 2.9x and 3.0, submitting a form in 2.9.x and 3.0, and using the switcher.

**Comment by klhall1987** [comment]
Tested ready for merge passing to @kstover

**Pull request merged**
