### PR TITLE
Deprecate v2.9.x API and Helper Functions

### PR DESCRIPTION
**Pull request by kjohnson**

### CODE REVIEW

**Comment by kjohnson** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;z3SGgglT&#x2F;61-deprecate-v2-9-x-functions"> Deprecate v2.9.x Functions</a>

**Comment by kjohnson** [comment]
Here are my manual tests for the deprecated functions: https://gist.github.com/kjohnson/968f4ed53be08173fe87d227ce575617

**Comment by klhall1987** [comment]
- [ ] ninja_forms_insert_field()
- [ ] ninja_forms_get_form_ids_by_post_id()
- [ ] ninja_forms_get_field_by_id()
- [ ] ninja_forms_get_fields_by_form_id()
- [ ] ninja_forms_get_all_fields()
- [ ] ninja_forms_update_field()
- [ ] ninja_forms_delete_field()
- [ ] nf_get_sub_count()
- [ ] nf_get_fields_by_form_id()
- [ ] Helper Functions

## Helper Functions
- [ ] ninja_forms_addslashes_deep()
- [ ] utf8_encode_recursive()
- [ ] ninja_forms_str_replace_deep()
- [ ] ninja_forms_html_entity_decode_deep()
- [ ] ninja_forms_htmlspecialchars_deep()
- [ ] ninja_forms_stripslashes_deep()
- [ ] ninja_forms_esc_html_deep()
- [ ] nf_wp_kses_post_deep()
- [ ] ninja_forms_strip_tags_deep()

**Comment by klhall1987** [comment]
`ninja_forms_insert_field()` if a field is being inserted using this function then, I'm not being able to open the field to edit it and I'm getting a JS error in the console. I've included a screenshot below. 

Screenshot: 
screen shot 2016-09-12 at 5 06 13 pm

**Comment by klhall1987** [comment]
`ninja_forms_get_form_ids_by_post_id()` is working in 3.0, but is not working in 2.9.x. 

I keep getting an empty array in 2.9.x even if the post has a form attached to it.

Replication Steps(in 2.9.x):
1. Create a new post. 
2. Append a Ninja Form then update the form. 
3. Write a function that uses `ninja_forms_get_form_ids_by_post_id()` to get the forms attached to the post you just created. 
4. Dump the results to the screen, you should receive an empty array.

**Comment by klhall1987** [comment]
Pushing to 3.0.10 milestone. Since I was out last week.

**Comment by kstover** [comment]
I'm going to close this PR so that we can re-group and attack it again with fresh eyes.

**Pull request closed without merging**
