### PR TITLE
Fix unserialize() error

### PR DESCRIPTION
**Pull request by todeveni**
Serialization is broken. Around "New Hampshire" there's a "3" where ";" should be.

Notice: unserialize(): Error at offset 2588 of 4500 bytes in ninja-forms/deprecated/includes/database.php on line 175

### CODE REVIEW

**Comment by klhall1987** [comment]
Hi @todeveni,

I'm having trouble replicating the notice shown in your comment locally. Would you mind to provide us with replication steps?

**Comment by todeveni** [comment]
I'm able to reproduce the bug with a clean install using [WP-CLI](http://wp-cli.org/) to install latest WordPress and latest Ninja Forms plugin.

```
$ wp core download
$ wp core config --dbname=ninjatest --dbuser=wp --dbpass=wp --extra-php <<PHP
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
PHP
$ wp core install --url=http://ninja.test --title="Ninja Forms test" --admin_user=admin --admin_password=password --admin_email=admin@ninja.test
$ wp plugin install ninja-forms --activate
```

Log in to `wp-admin` and open up the default "Contact Form". Check `wp-content/debug.log`.

If you have PHP display_errors enabled, you should see the error in the admin too. I'm using xdebug on my dev environment.
image

**Comment by walterebert** [comment]
I had the same problem and the patch worked for me.

**Comment by kjohnson** [comment]
@klhall1987 please test with the above mentioned reproduction steps.

**Comment by kjohnson** [comment]
@klhall1987 Ping.

**Comment by klhall1987** [comment]
Working on this PR now.

**Comment by klhall1987** [comment]
Tested and fix is working passing to @kjohnson to merge.

**Pull request merged**
