### PR TITLE
Refactored Form Ajax Controller

### PR DESCRIPTION
**Pull request by iamntz**
Reduced the size of the main method by extracting all stuff into their own methods.

There is no other functionality introduced and the purpose is solely to make things easier to read.

---

Btw, there is any kind of automated testing available?

### CODE REVIEW

**Comment by iamntz** [comment]
Btw, since the docs for NF3 is still scarce, I'm digging a lot into the NF core code and I notice some methods (or classes) that are quite long.

I would gladly take care of their readability if that's ok with you, guys.

**Comment by kjohnson** [comment]
Hey @iamntz, thanks for the work that you are doing with Ninja Forms. We greatly appreciate when the Ninja Forms community gets involved.

I have it on my list to refactor the AJAX controllers, but I'll review what you have here. :)

Thank you for contributing!

**Comment by kjohnson** [comment]
@iamntz It looks like there are merge conflicts. Once you fix them I can merge this.

**Comment by iamntz** [comment]
I force pushed the patch because I wasn't able to take care of the conflicts in a clean way. I think it's ok now.

**Comment by kstover** [comment]
@kjohnson I need input on this, please.

**Comment by kjohnson** [comment]
@kstover looks good to me. I will have to resolve a few merge conflicts, but this looks good.

**Comment by kstover** [comment]
@kjohnson Need you to look at the conflicts so that we can work on merging, this, please.

**Comment by klhall1987** [comment]
@kjohnson would you mind to fix these merge conflicts.

**Comment by kjohnson** [comment]
As we modify this class for performance reasons I'm going to have to close this PR.
@iamntz I liked your changes, but it is now moot. Sorry for not merging this earlier.

**Comment by iamntz** [comment]
Cool, no problem. Probably would be better to decide on a PR action sooner than 6 months 😸

**Pull request closed without merging**
