### PR TITLE
Added Delete All Submissions Button

### PR DESCRIPTION
**Pull request by jacobschweitzer**
Added button and functionality for deleting all submissions for a
selected form. This addresses wpninjas/ninja-forms#810 .

### CODE REVIEW

**Comment by kstover** [comment]
Hey @jacobschweitzer,

I'll get @kjohnson to look this over in the next week or so. We're updating Ninja Forms from the ground up now, but the submission system isn't changing very much.

**Comment by jacobschweitzer** [comment]
Added some more changes just now for formatting and query arguments.

**Comment by kjohnson** [comment]
@jacobschweitzer Everything seems to functioning :)

Just a couple of things, though:
- We'd like to see a confirmation box before deleting all subs, as this could be dangerous .
- This needs to be pulled against the 2.9.28 branch, as we are releasing from there, temporarily, as we move towards 3.0.

**Comment by jacobschweitzer** [comment]
Alright thanks for the feedback Kyle, I will work on those two items.

**Comment by kjohnson** [comment]
@jacobschweitzer we are about to release 2.9.29, and will be creating a 2.9.x branch for future 2.9.x pull requests. Please re-submit your pull request against the 2.9.x branch, as we cannot make that change for you.

**Pull request closed without merging**
