### PR TITLE
Add Field List Setting for Actions

### LINKED ISSUE #1632: Add Setting Convention for Field Toggle List
Add a setting convention for displaying a fieldset of toggles for fields. This is similar to the field select setting, but allows for selecting multiple fields.

This is a blocker for the File Uploads add-on.

Also, this new setting can be used for the Save action.

### PR DESCRIPTION
**Pull request by kjohnson**
- Add new action setting "Field List"

Closes #1632 .

### CODE REVIEW

**Comment by polevaultweb** [comment]
@kjohnson Branch needs a merge of `master`. @klhall1987 any udpate on testing?

**Comment by kjohnson** [comment]
@klhall1987 put this at the top of your list for tomorrow.

**Comment by klhall1987** [comment]
@polevaultweb Testing now :)

**Comment by klhall1987** [comment]
Basic contact form is failing to upgrade to 3.0 in this branch. I'm getting a JS console error and a PHP error. I've detailed both of the errors in screenshots below. 

Screenshots: 
PHP Errorlog: 
screen shot 2016-08-26 at 12 53 47 pm

JS Console Error: 
screen shot 2016-08-26 at 1 00 41 pm

Replication Steps(on this branch starting in 2.9.x):
1. Create a basic contact form. 
2. Upgrade to 3.0.

**Comment by kjohnson** [comment]
@klhall1987 rebase on master. I changed the form import feature, which is used by the upgrade process.

**Comment by klhall1987** [comment]
@kjohnson this PR now has a merge conflict. Would you mind to clear the merge conflict before I continue testing?

**Comment by klhall1987** [comment]
Tested and merged.

**Pull request merged**
