### PR TITLE
Calculation Refactor

### LINKED ISSUE #2451: Improving Calcs
- [x] Context for Merge Tags - ":calc" on list fields or pulls value (fix context so that it always pulls 'calc' if it exists, then value if calc is unset)
- [x] Rounding setting to calculations (add option of round to x amount of decimal points beneath calc label in builder)
- [x] Save calculations as extra value and show them on submission editing screen and export with submissions
- [x] Remove math.min.js and math.min.js.map and replace its function calls with vanilla js
- [x] Calculations should be available in all merge tags contexts within emails and actions
- [x] Apply padding to calculation content box to avoid overlapping with the merge tag icon
- [x] Calculation content box needs to have key tracking for merge tags it contains

### PR DESCRIPTION
**Pull request by Much2tall**
Closes #2451 .

### CODE REVIEW

**Comment by kstover** [comment]
@Much2tall When you edit a calculation by adding/editing the decimal setting, an error is being applied to the settings of the calculation that causes red lines to appear underneath them.

**Comment by kstover** [comment]
@Much2tall If the "decimals" setting is empty, assume 2 decimal places rather than 0.

**Comment by Much2tall** [comment]
@kstover Both issues resolved.

**Comment by Much2tall** [comment]
Closes: https://github.com/wpninjas/ninja-forms/issues/2541

**Pull request merged**
