### PR TITLE
Updated fix for Recaptcha

### LINKED ISSUE #1298: Allow multiple recaptcha fields on the same page
A user has requested the ability to add multiple recaptcha fields on a page. Currently if a page has multiple recaptcha fields on a page, only one recaptcha field will show and a console error is thrown that states, "Uncaught Error: ReCAPTCHA placeholder element must be empty".  The user( Revxx14 ) sent us a gist showing us how they modified the ninja-forms-recaptcha.php in 2.9.x to solve this issue. 

Revxx14's GIst:
https://gist.github.com/revxx14/544a72290e042293164d169b10a92318

### PR DESCRIPTION
**Pull request by Dwarve**
Updated the recaptcha fix to be compatible with latest dev branch.
Closes #1298

### CODE REVIEW

**Comment by Dwarve** [comment]
@kjohnson It was easier to just create a new branch and start from scratch with a fresh pull from develop branch. This was tested with multiple forms on the same page and a recaptcha in each. 1 of which was an invisible version so it should be fully compatible with those additions as well. I'm closing the PR #2995 with a reference to this new PR as well.

**Comment by kjohnson** [comment]
@Dwarve awesome. Sorry for goofing the merge of the previous PR.

**Comment by floppyTop** [comment]
Hi all,

This issue is still able to be re-produced intermittently.
Please see the top error following example screenshot:
https://i.imgur.com/NPOl9e8.png

**Comment by floppyTop** [comment]
Hi @kjohnson and @Dwarve ,

This issue is still able to intermittently be reproduced when two ReCaptchas are on one page.

Please see the top error in the screenshot:
https://i.imgur.com/NPOl9e8.png

**Pull request merged**
