### PR TITLE
Currency Settings

### LINKED ISSUE #1192: Add currencies to currency picker in form settings
Currently only USD available

### LINKED ISSUE #1476: Add Currency Plugin Setting

### LINKED ISSUE #1477: Add Currency Payment Gateway Setting
Include 'form default' default option.

### PR DESCRIPTION
**Pull request by kjohnson**
Closes #1477.
Closes #1476.
Closes #1192.

### CODE REVIEW

**Comment by kjohnson** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;TzvLwEKF&#x2F;31-currency-symbol-doesn-t-change-from"> Currency Symbol doesn&#39;t change from &quot;$&quot; </a>

**Comment by kstover** [comment]
@kjohnson What's the status of this PR?

**Comment by kjohnson** [comment]
@kstover looks like it needed some merge conflicts to be resolved before further testing.

**Comment by klhall1987** [comment]
@kjohnson Could you resolve merge conflicts before I test this PR?

**Comment by kjohnson** [comment]
@klhall1987 merge conflicts resolved.

**Comment by klhall1987** [comment]
Tested working correctly however, https://github.com/wpninjas/ninja-forms-paypal-express/pull/23 needs to be released along with this PR in order to fix an issue with the currency symbol not being sent to Paypal. Passing to @kstover to merge.

**Pull request merged**
