### PR TITLE
1st pass a11y for front end

### PR DESCRIPTION
**Pull request by roborourke**
Closing #2896 in favour of this - using correct base this time!

I've done some preliminary testing with VoiceOver on mac - toggle it using command+f5.

It's quite chatty but seems ok. Ideally it should be tested by someone who's far more used to it but this is certainly a step in the right direction.

Also you should double check I haven't broken anything adding in the aria-invalid attribute behaviour!

Props to @rianrietveld for the advice.

### CODE REVIEW

**Comment by roborourke** [comment]
@kstover anything I can do to help with this one?

**Comment by kstover** [comment]
Hey @roborourke! Sorry for the delay in getting back to you. I'll look over this later today; we have a release going out, but I don't think I'll have time to get this fully tested before it goes out.

I'll make sure that it gets out in the next one.

**Comment by roborourke** [comment]
No worries, can see you've been busy :)

**Comment by kstover** [comment]
Merged. Thanks again!

**Comment by roborourke** [comment]
🙌 awesome!

**Pull request merged**
