### PR TITLE
Localize ninja forms for fr_CA

### PR DESCRIPTION
**Pull request by audiovisuel-uqam**
For all intents and purposes the language will be identical to fr_FR
Cloned from:
ninja-forms-fr_FR.po
ninja-forms-fr_FR.mo

### CODE REVIEW

**Comment by kstover** [comment]
Hi. Thanks for submitting the PR!

I'm having some trouble generating the .mo file from this .po. Could you update the PR with the .mo?

**Comment by kjohnson** [comment]
@kstover shouldn't this be added via WordPress.org/Glotpress.

**Comment by kstover** [comment]
@kjohnson I'm not sure how the fr_CA affects that. We'd probably need to reach out to someone on the Glotpress team.

**Comment by kjohnson** [comment]
@audiovisuel-uqam to my understanding, this should be submitted via Glotpress at WordPress.org
https://translate.wordpress.org/locale/fr-ca/default/wp-plugins/ninja-forms

**Pull request closed without merging**
