### PR TITLE
Render.php / NF_Display_Render class refactor

### PR DESCRIPTION
**Pull request by iamntz**
I'm doing some refactorings on this class because it have some huge methods and some code duplication.

For some reasons, the display method is called... localize. Any particular reasons on that? Or i'm free to rename the method (and leave the old name in place, for compatibility reasons)?

### CODE REVIEW

**Comment by iamntz** [comment]
Alright, so the first stage is complete. I refactored the `localize` method by extracting most of the tuff into small, contained methods. There is some duplication inside the preview method, but that's a subject for another PR.

Also, this contains a tweak on submission counter when a form has a max allowed submissions.

**Comment by kstover** [comment]
@kjohnson Need input on this, please.

**Comment by kjohnson** [comment]
@kstover generally looks good to me, but I'll need to take a closer look.

**Comment by klhall1987** [comment]
Pushing to 3.0.10 milestone. Since I was out last week.

**Pull request closed without merging**
