### PR TITLE
Recaptcha Fix

### LINKED ISSUE #1298: Allow multiple recaptcha fields on the same page
A user has requested the ability to add multiple recaptcha fields on a page. Currently if a page has multiple recaptcha fields on a page, only one recaptcha field will show and a console error is thrown that states, "Uncaught Error: ReCAPTCHA placeholder element must be empty".  The user( Revxx14 ) sent us a gist showing us how they modified the ninja-forms-recaptcha.php in 2.9.x to solve this issue. 

Revxx14's GIst:
https://gist.github.com/revxx14/544a72290e042293164d169b10a92318

### PR DESCRIPTION
**Pull request by Dwarve**
Fixes the multiple recaptcha issue where having multiple forms on the
same page would conflict. Closes #1298

### CODE REVIEW

**Comment by floppyTop** [comment]
Hello @Dwarve 

Will this be merged at any point soon? We have a project in progress where this is a critical fix, and we really would prefer to not update the core files ourselves.

**Comment by rhamses** [comment]
This fix would resolve issues with two forms on the same page and with Total Cache activate? Because if it does, would be really nice if gets merged.

**Comment by ignaty** [comment]
Can that could be merged soon? :)

**Comment by kjohnson** [comment]
Welp! I done goofed up that merge... Need to re-incorporate the recent addition of support for the Invisible reCAPTCHA changes.

**Comment by kjohnson** [comment]
@Dwarve Can you `pull` the `develop` branch and re-submit? PR #2638 contains major reCAPTCHA changes and was merged just before I tried to merge this one (and I goofed the merge).

**Comment by floppyTop** [comment]
Hi @kjohnson and @Dwarve ,

Will you guys have time to work on this soon? Our project is nearing deadline and there are two massive forms on the homepage that could really use this fix.

Kindest regards,
Matt

**Comment by Dwarve** [comment]
New PR submitted. #3053 is the new PR that includes full resolution between the two updates. I'm closing this PR in favor of the new one.

**Comment by floppyTop** [comment]
Hi @kjohnson and @Dwarve ,

This issue is still able to intermittently be reproduced when two ReCaptchas are on one page.

Please see the top error in the screenshot:
https://i.imgur.com/NPOl9e8.png

**Pull request closed without merging**
