### PR TITLE
Check for subject type before calling preg_match_all (#2720)

### PR DESCRIPTION
**Pull request by isleshocky77**
preg_match_all expects the subject to be a string, we handle the case
of it not being a string below this line; however, having it here throws
off a warning.

for #2720

### CODE REVIEW

**Comment by isleshocky77** [comment]
Thanks @kstover

**Comment by isleshocky77** [comment]
@kstover I was just reviewing your PR Merge and realized I introduced a bug. Do you want me to push to the same branch or a new PR off of master?

**Comment by kstover** [comment]
Just push to this branch.

**Comment by isleshocky77** [comment]
@kstover Ok. It doesn't seem my code created a bug, it looks like there was a block of code which you couldn't get to before my addition. I'll open a new issue and this can now be closed.

**Pull request merged**
