### PR TITLE
Rework frontend data loading

### PR DESCRIPTION
**Pull request by kstover**

### CODE REVIEW

**Comment by klhall1987** [comment]
It looks like the fields drawer is sticking out little bit in the form builder on my thunderbolt in this branch. I've detailed what I'm seeing in an image below.

Screenshot: 
 http://goo.gl/KhYdx3

Replication Steps(in 3.0): 
1. Open the builder on a thunderbolt.

**Comment by kstover** [comment]
Do you have any extensions activated? Or is it just core?

**Comment by klhall1987** [comment]
Just core.

**Comment by kjohnson** [comment]
+1

**Comment by klhall1987** [comment]
Tested and I'm not seeing any glaring issues. Let's merge it for additional testing in core.

**Pull request merged**
