### PR TITLE
custom notification triggers

### PR DESCRIPTION
**Pull request by helgatheviking**
allow notifications to skip processing on default form submission. for #458. No idea, if this is the best approach, but it does allow the the PayPal IPN notification I am working on to not be emailed when the form is submitted. Then it can be called by a custom trigger when the IPN is confirmed.

### CODE REVIEW

**Comment by kstover** [comment]
Hey. I'm closing this because we're in the middle of a plugin re-write. This issue should be taken care of when we come out of that re-write!

**Comment by helgatheviking** [comment]
Great. I had been meaning to ask you guys how the re-write was going? I need to make a decision on how to do a donation form for a project. I understand if you can't give me an ETA, but is the re-write something you expect relatively soon or is it still a long ways off?

**Comment by kstover** [comment]
It's something that we plan on launching for realz in December, but we'll have an alpha of core out early October.

**Comment by helgatheviking** [comment]
Thanks Kevin! best of luck with the re-write, it sounds like it is going to be awesome.

**Comment by kstover** [comment]
No problem! It's going to be pretty sweet. We've got our dev team on a crazy blitz for this month. The team is next door to me, working on the new Field Registration class. It sounds pretty awesome. :)

You can follow the issues tagged with 3.0 dev to get a sense of where we are. :)

**Pull request closed without merging**
