### PR TITLE
Remove jQuery.html() call on Help Text

### PR DESCRIPTION
**Pull request by kjohnson**

### CODE REVIEW

**Comment by klhall1987** [comment]
Some styling not being applied. This might be due to the merge conflict.

Screenshot: 
http://goo.gl/neul4b

**Comment by klhall1987** [comment]
Received fatal error detailed in screen shot below when using "Start from a template" functionality. This also could be due to the merge conflict. 

Screenshot:
screen shot 2016-05-26 at 1 50 54 pm

**Comment by klhall1987** [comment]
@kjohnson I'm going to move on from the PR. Let me know when the merge conflict is resolved and I'll come back and test.

**Comment by kjohnson** [comment]
@klhall1987 merge conflicts resolved.

**Comment by klhall1987** [comment]
@kjohnson This branch has merge conflicts please let me know when they are fixed and I'll test this PR.

**Comment by kstover** [comment]
@kjohnson @klhall1987 Need input on this, please.

**Comment by kjohnson** [comment]
@kstover confirmed that this is still relevant. Passing to @klhall1987 to test.

**Comment by klhall1987** [comment]
@kjohnson Could you mind to fix these merge conflicts before testing.

**Pull request merged**
