### PR TITLE
Add CSS optimization using cssnano (#2538)

### LINKED ISSUE #2316: Column classes not working in IE11
one-half and one-half first are the classes used here:

image

Works well in other browsers.

Attached forms are examples.  They use MPF as well, but the issues are present regardless of MPF.

[587d4e55bcf4521100876365-nf_form_01_16_2017_contact.txt](https://github.com/wpninjas/ninja-forms/files/712177/587d4e55bcf4521100876365-nf_form_01_16_2017_contact.txt)
[587d4e55bcf4521100876364-nf_form_01_16_2017_property.txt](https://github.com/wpninjas/ninja-forms/files/712176/587d4e55bcf4521100876364-nf_form_01_16_2017_property.txt)

### PR DESCRIPTION
**Pull request by amt925**
This adds functionality requested in #2538 and also will fix #2316

### CODE REVIEW

**Comment by kstover** [comment]
@jameslaws Could you look over this and let me know what you think?

**Comment by amt925** [comment]
Any chance this will be added to an upcoming release?

**Comment by kjohnson** [comment]
@amt925 this would fall on @jameslaws 's plate for review. However, he is currently out of town.

**Comment by amt925** [comment]
@kjohnson thanks for the update

**Comment by kjohnson** [comment]
@amt925 LGTM. We actually have a release going out right now, but I'm slating this for the following release.

@kstover after merging I want to go through and re-organize/comment this file (before the next release).

**Comment by amt925** [comment]
Great, thanks!

**Comment by amt925** [comment]
Any update on this?
Would be great if this could be added because my custom styles were borken by this change: https://github.com/wpninjas/ninja-forms/commit/65531f99f13afee585e94009de3c993bde758084#diff-d345b5fc10729a606e6b599bdc47bd22

**Comment by kstover** [comment]
@kjohnson Do we want to get this into 3.1.5 or 3.1.6?

**Pull request merged**
