### PR TITLE
First pass at adding WP Session Manager to Ninja Forms.

### PR DESCRIPTION
**Pull request by kjohnson**
**Test Forms**

- [x] PayPal ( Logged In )
- [x] Redirect to page that uses the [ninja_forms_field id=] shortcode. ( Logged In )
- [x] PayPal ( Logged Out - Incognito )
- [x] Redirect to page that uses the [ninja_forms_field id=] shortcode. ( Logged Out - Incognito )

### CODE REVIEW

**Comment by wpnzach** [comment]
**Test Forms**

- [ ] PayPal ( Logged In )
- [ ] Success Message with Field Values ( Logged In )
- [ ] PayPal ( Logged Out - Incognito )
- [ ] Success Message with Field Values ( Logged Out - Incognito )

**Comment by kstover** [comment]
**Test Forms**

- [ ] PayPal ( Logged In )
- [ ] Success Message with Field Values ( Logged In )
- [ ] PayPal ( Logged Out - Incognito )
- [ ] Success Message with Field Values ( Logged Out - Incognito )

**Comment by kjohnson** [comment]
I had to rebase the branch on master, because of a JS error fix that wasn't applied, but all four tests passed.

**Comment by kstover** [comment]
Just added some code to force the use of WP Session over the PHP $_SESSION. Tested with php.ini disabled sessions and it works for me as well.

**Comment by wpnzach** [comment]
All 4 tests with no issues on my local install, PHP 5.6

**Pull request merged**
