### PR TITLE
deprecate Ninja Forms 2.*. Closes #857 .

### LINKED ISSUE #857: Deprecate Ninja Forms Core 2.*

### PR DESCRIPTION
**Pull request by kjohnson**
- [x] Create a New Form
- [x] Display the Form
- [x] Create an Email
- [x] Create required field. 
- [x] Create a Success Message
- [x] Create a Redirect (separate form)
- [x] Submit the Form
- [x] Fire an Email Action
- [x] Receive Email
- [x] See Success Message
- [x] See Redirect (separate form)
- [x] Edit the Form
- [x] View Submissions
- [x] Edit Submission
- [x] Delete an Action
- [x] Delete the Form

### CODE REVIEW

**Comment by klhall1987** [comment]
All conditions above were tested and passed.

**Comment by wpnzach** [comment]
- [x] Create a New Form
- [x] Display the Form
- [x] Create an Email
- [x] Create required field. 
- [x] Create a Success Message
- [x] Create a Redirect (separate form)
- [x] Submit the Form
- [x] Fire an Email Action
- [x] Receive Email
- [x] See Success Message
- [x] See Redirect (separate form)
- [x] Edit the Form
- [x] View Submissions
- [x] Edit Submission
- [x] Delete an Action
- [x] Delete the Form

**Comment by wpnzach** [comment]
Is this error related?

WordPress database error: [Table 'wordpress.wp_ninja_forms' doesn't exist]
SELECT * FROM wp_ninja_forms WHERE id = 1


Warning: Invalid argument supplied for foreach() in /Users/zskaggs/Documents/WordPress/wp-content/plugins/ninja-forms-front-end-editor/includes/display/fields/profile-meta-filter.php on line 13

Warning: Invalid argument supplied for foreach() in /Users/zskaggs/Documents/WordPress/wp-content/plugins/ninja-forms-front-end-editor/includes/display/fields/post-meta-filter.php on line 9

**Comment by wpnzach** [comment]
In submissions view, there is a bug where the actions are displayed twice: https://goo.gl/w9JxNP

**Comment by wpnzach** [comment]
This weird ghost form randomly appeared during testing: https://goo.gl/KPGvEC

**Comment by kstover** [comment]
@wpnzach If you submit again, does the second submission have the same duplicated actions row?

**Comment by kstover** [comment]
@wpnzach That appears to be something specific to Front End Editor.

**Comment by kstover** [comment]
@wpnzach If you delete all your forms and create a new one, does another ghost form appear?

**Comment by wpnzach** [comment]
@kstover No ghost form on second try, still getting the duplicated actions row on every submission.

**Comment by kstover** [comment]
@wpnzach I don't get either a ghost form or duplicated submission actions. I'm going to mark this as ready to go.

**Pull request closed without merging**
