### PR TITLE
Add processed_fields tracking.

### LINKED ISSUE #2433: Collect action redirect processes fields again.
To recreate

1. Create form with file upload field
2. Set the FU field to save to media (this forces a fatal error)
3. Add PayPal plugin with sandbox creds
4. Add Collect Payment action in sandbox mode with total.
5. Submit form, pay in PP.
6. Form processes the FU upload once before the redirection to PP and once after.
7. The tmp FU is deleted on the second process and causes an error.

https://wpninjas.kustomerapp.com/app/customers/58421aaf24f5391100db1656/event/58a369714b70bd110086336f

### PR DESCRIPTION
**Pull request by kjohnson**
Closes #2433.

### CODE REVIEW

**Comment by polevaultweb** [comment]
Fixes added via https://github.com/wpninjas/ninja-forms/pull/2458 and works :)

**Comment by kjohnson** [comment]
Also proposing #2472.

**Comment by kstover** [comment]
We need to make sure that this tested with PayPal.

**Comment by kjohnson** [comment]
Tested with PayPal on a customer's site and it didn't seem to work as expected.

(Also, I think I foobar'd the rebase. Whoops!)

**Pull request closed without merging**
