### PR TITLE
swap out decimal separator. Closes #848 .

### LINKED ISSUE #848: Calcs are a B

### PR DESCRIPTION
**Pull request by kjohnson**

### CODE REVIEW

**Comment by kstover** [comment]
@kjohnson Thanks for tracking this down!

**Comment by klhall1987** [comment]
Tested the following conditions were tested and passed: 

Add two number fields.
Subtract two number fields. 
Multiply two number fields.
Divide two number field.

Add two calc fields. 
Subtract two calc fields. 
Multiply two calc fields.
Divide two calc fields. 
 
Add three calc fields.
Subtract three calc fields.
Multiply three calc fields.
Divide three calc fields.

**Comment by kjohnson** [comment]
Woot!

**Comment by kjohnson** [comment]
Received customer confirmation that this fix resolves his calculation issue.

**Pull request merged**
