### PR TITLE
Remove unused function arguments for refresh_plugin_settings()

### PR DESCRIPTION
**Pull request by wpnzach**
removed arguments from refresh_plugin_settings

### CODE REVIEW

**Comment by wpnzach** [comment]
closes 735

**Comment by kjohnson** [comment]
Do these need to be kept for backwards compatibility? If this is used anywhere with arguments, then removing them from the function declaration will throw an error.

**Comment by kstover** [comment]
It is referenced one other place in core, and I can change that.

**Comment by kstover** [comment]
None of our extensions reference it.

**Pull request merged**
