### PR TITLE
Add reCAPTCHA Field

### PR DESCRIPTION
**Pull request by amansaini**
Adds a google reCAPTCHA field.

I have added the site key, secret & language under general setting, let me know if it should be somewhere else.

screen shot 2015-04-24 at 7 53 50 pm

The new reCAPTCHA field is available under template fields section on edit form page.

screen shot 2015-04-24 at 7 59 22 pm

### CODE REVIEW

**Comment by kstover** [comment]
@amansaini Sorry that I'm just getting to this pull request! I have a couple of notes:

1) Let's add a link to the page that let's you register for a google recaptcha API key underneath the key field. This will help new users, I think.
2) If I add a reCaptcha field, and I haven't saved the field settings, I get an undefined notice when I preview my form.

**Comment by amansaini** [comment]
Hey @kstover 
Thanks for your feedback.
I have added url to get site key and also a check to show the recaptcha field only if site and secret key values are saved.
Since it is a required field by default so I have also added a hidden field. It's value is updated with response recaptcha sends to callback function when captcha is successfull. If value is empty then user gets standard "This field is required" error on form submission.

I am using localhost when generating keys and tested it locally, seems to work fine.

**Comment by kjohnson** [comment]
ping @kstover

**Comment by kstover** [comment]
This looks good to me. Good job @amansaini!

I have a few minor English fixes that I've taken care of locally, and will merge once this is merged into Core. I've also moved the reCaptcha settings to their own metabox.

Assigning this to @kjohnson now, and once he's gone over it, we'll be merging.

**Comment by kjohnson** [comment]
`Notice: Undefined variable: field_class in /var/www/wp-content/plugins/ninja-forms/includes/fields/recaptcha.php on line 40`

**Comment by kstover** [comment]
@amansaini Thanks again for the commit. This is fully integrated into core now. It will go live with the next release.

**Comment by amansaini** [comment]
@kstover  cool :+1:

**Pull request merged**
