### PR TITLE
[Uninstall] Remove Options and v2.9.x Tables.

### LINKED ISSUE #1834: Uninstall hook cleanup
2.9.x Tables
- [x] `nf_objectmeta`
- [x] `nf_objects`
- [x] `nf_relationships`
- [x] `ninja_forms_fav_fields`
- [x] `ninja_forms_fields`

Options
- [x] `ninja_forms_settings`
- [x] `ninja_forms_load_deprecated`
- [x] `ninja_forms_allow_tracking`
- [x] `ninja_forms_do_not_allow_tracking`

### LINKED ISSUE #2399: Forms and submission data not being cleared on uninstall with "Remove ALL Ninja Forms data upon uninstall?" checked
When deleting the plugin with "Remove ALL Ninja Forms data upon uninstall?" checked under Settings>Advanced Settings, forms and submission data is not being cleared/is still present after reinstall. I tested this both on a normal install and a multisite install after seeing this issue: https://github.com/wpninjas/ninja-forms/issues/2170

Reproduction steps:
1) Create a form, attach it to a page, and submit it a few times
2) Under Forms>Settings>Advanced Settings, check "Remove ALL Ninja Forms data upon uninstall?"
3) Uninstall the plugin
4) Reinstall the plugin. Forms and submission data are still there.

### PR DESCRIPTION
**Pull request by kjohnson**
Closes #1834.
Closes #2399.

- [x] Drop v3 Tables
- [x] Drop v2 Tables
- [x] Delete Options
- [x] Un-schedule Cron

--

- Delete Submissions (Separate PR)

### CODE REVIEW

**Comment by klhall1987** [comment]
@kjohnson this PR does not seem to work. I have 'Remove ALL Ninja Forms data upon uninstall?" check, yet after deactivating and deleting Ninja forms core all my tables and it didn't look like anything was deleted at all. I ran this test twice with the same result.

**Comment by kstover** [comment]
I just tested, and it doesn't appear to be deleting anything.

@kjohnson Can you get eyes on this when you get a chance? We really need to make sure that it's working properly.

**Comment by klhall1987** [comment]
I'm still seeing the 2.9.x tables in my database when testing. I'm also stilling seeing cached data, I'm not sure if that matters or not.

**Comment by kstover** [comment]
@kjohnson What's the status of this PR?

**Comment by jmcelhaney** [comment]
The forms get removed and the tables dropped in the 2.9.x codebase, but not in the 3.0 codebase.

**Comment by klhall1987** [comment]
I got the following error upon trying to delete Ninja Forms core with the nuke setting on. 

screen shot 2017-05-01 at 3 51 20 pm

**Comment by klhall1987** [comment]
However all my Ninja Forms tables were gone.

**Comment by kstover** [comment]
Still seeing this error when I run the delete:

Deletion failed: WordPress database error: [You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near &#039;&#039; at line 1]SELECT blog_id FROM WordPress database error: [You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near &#039;&#039; at line 1]SELECT blog_id FROM {"success":true,"data":{"delete":"plugin","slug":"ninja-forms","plugin":"ninja-forms-issue-1834\/ninja-forms.php","pluginName":"Ninja Forms"}}

**Pull request merged**
