### PR TITLE
Add output buffer check for shortcodes in default values

### LINKED ISSUE #1831: HTML fields do not parse shortcodes.

### PR DESCRIPTION
**Pull request by kjohnson**
Closes #1831.

### CODE REVIEW

**Comment by klhall1987** [comment]
@kjohnson I'm a little confused by this PR, I tested a shortcode plugin I wrote on the develop branch and displayed the text I echoed out on the front end. I switch over to the PR branch and it shortcode no longer echoed on the frontend.

**Comment by jameslaws** [comment]
Can you share your shortcode plugin? I think this is to handle issues with shortcodes built incorrectly.

**Comment by klhall1987** [comment]
`
function test()
{
    echo 'foo';
}
add_shortcode( 'foobar', 'test' );
`

That's my plugin.

**Comment by jameslaws** [comment]
Ok, so that shortcode is incorrect. :)

https://codex.wordpress.org/Shortcode_API#Output

**Comment by klhall1987** [comment]
Okay cool, that make sense now. I'll add the output buffer stuff and retest. Thanks for your help :)

**Comment by klhall1987** [comment]
After adding the output buffer stuff @jameslaws pointed me to, everything worked correctly. Merging into master.

**Pull request merged**
